###########################################################################################################################
# setup workflows ##
version: 2.1
#
## denotes that it is setup workflow
setup: true
#
## using the path filtering orb
orbs:
  path-filtering: circleci/path-filtering@0.1.1
#
## workflow using path-filtering orb (w/ built in continuation)
workflows:
 setup-workflow:
   jobs:
     - path-filtering/filter:
         base-revision: main
         config-path: .circleci/continue-config.yml
         mapping: |
           mysite/.* mysite true
           polls/.* polls true
           .circleci/.* circle-ci true
           docs/.* docs true
           shared/.* run-them-all true
           